name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup dart environment
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
      - name: Check dart format
        run: ./tool/check-dart-fmt.sh
      - name: Analyze project source
        run: dart analyze
      - name: Run tests
        run: dart test
